### ISSUE TITLE
"Audio Clip Length" Pads Lighting  #PushOne

### ISSUE THREAD

**Issue by florianwns** [git-moss/DrivenByMoss#352] opened 2023-04-15 19:48 UTC
Hi everyone and Thx a lot Moss for your amazing works.
I rediscovered the joy of programming music thanks to push 1, bitwig but above all your great programming work.
As a developer, I know how hard it is to keep things up to date, to make changes and I'm sure that will require a daily and constant effort from you and for that, avery big "THANK YOU".

I'm happy to see that open source has joined the computer music world.

-------

I found a very little interface bug with my ableton push 1.
It's at the level of the Clip Length Note mode (or "ClpLngt" on my push) refresh.
When I switch between the "Session" and "Note" buttons, I need to change the audio track so that the pads light up again.

Step to reproduce:
* Open a new project
* Add 3 Tracks for example : Audio, Midi, Audio
* For Midi Track 2, Select "Drum" Note mode 
* For Audio Track 1, and 3: Select "ClpLngt" Note mode
* Select Track 3
* Switch between buttons "Sessions" -> "Note"
* Clip length Pads for are now hidden <<< THE ISSUE >>>
* Select Track 1: Clip length Pads are on
* Select Track 3: Clip length Pads are now on again

MySystem:
* Mac OS X Mojave
* Drive: DrivenByMoss-19.2.2-Bitwig.zip
* Bitwig 4.4

Thx for your help

**Comment by git-moss** [comment] 2023-04-17 20:47
Thanks for the detailed description! I was running into this from time to time but could not reproduce it. Will be fixed in the next update!

**Closed by git-moss** 2023-04-17 20:47 UTC
