### ISSUE TITLE
APC40: Editing notes parameters in the sequencer modifies always the first note

### ISSUE THREAD

**Issue by mcristi** [git-moss/DrivenByMoss#204] opened 2020-09-20 12:24 UTC
Pressing the pad of an existing note and turning the 8 mode knobs always affect the first note.

DrivenByMoss 10.6.4 & Bitwig 3.2.7

**Comment by git-moss** [comment] 2020-09-20 15:16
Tested both with Mk1 and Mk2 but cannot reproduce that. Can you please give more detailed step what you are doing?

**Comment by mcristi** [comment] 2020-09-20 16:42
I have disabled the other script I have to remove any interferences and left the default extension settings
<img width="543" alt="Screenshot 2020-09-20 at 19 21 43" src="https://user-images.githubusercontent.com/1414341/93716146-b505f280-fb76-11ea-88b7-b3ee587b4450.png">

I have a simple drum machine rack preset loaded
<img width="706" alt="Screenshot 2020-09-20 at 19 21 52" src="https://user-images.githubusercontent.com/1414341/93716177-e8e11800-fb76-11ea-9a54-29c3fae1d717.png">

And a 4 beats clip with 2 snare notes (coloured by velocity): C1 and E0 note message sent from Akai
Even if the E0 is pressed and the second knob is turned, only the first note is affected (see the gif below) 
![Screen-Recording-2020-09-20-at-1](https://user-images.githubusercontent.com/1414341/93716510-e97aae00-fb78-11ea-9d3c-92541768a5b1.gif)

**Comment by git-moss** [comment] 2020-09-20 19:00
I tried now also on Macos.
I am sorry but I still cannot reproduce that.

I just release a new version. Could you try with that one? Don't think that it changes anything but just to be sure.
Could also be interesting to see what you are doing on the controller.

**Comment by mcristi** [comment] 2020-09-21 09:24
I have just recorded a video with the actions on the controller using the latest release https://drive.google.com/file/d/1ByWT-pxt83wgf_zLM70ARoiKnxJIJwRp

Could you suggest me some relevant places in the code where to log/debug?

**Comment by git-moss** [comment] 2020-09-22 14:32
Thanks, that finally helped! There was the wrong variable used, therefore always notes from the first row were used.
Will be fixed in the next update.
It did only happen in the drum sequencer, not the drum sequencer, correct?

**Closed by git-moss** 2020-09-22 14:32 UTC

**Comment by mcristi** [comment] 2020-09-22 14:56
Indeed, the sequencer is not affected by this bug. 
Thanks a lot! 😎
